CREATE TABLE unaj.incidencias (
  `Tipo_id` int(1) NOT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `email` varchar(50) NOT NULL,
  `apellido` varchar(50) NOT NULL,
  `nombre` varchar(70) NOT NULL,
  `dni` varchar(12) NOT NULL,
  `telefono` varchar(14) DEFAULT NULL,
  `propuesta_codigo` varchar(45) DEFAULT NULL COMMENT 'Codigo de la carrera.',
  `propuesta_descripcion` varchar(200) DEFAULT NULL,
  `elemento_codigo` varchar(100) DEFAULT NULL COMMENT 'Codigo de la materia.',
  `elemento_descripcion` varchar(200) DEFAULT NULL,
  `Id_area` int(1) DEFAULT NULL,
  `tipo_incidencia` int(1) NOT NULL,
  `descrip_incidencia` varchar(3000) DEFAULT NULL,
  `estado` int(1) NOT NULL,
  `fecha_creacion` date NOT NULL,
  `username` varchar(20) DEFAULT NULL,
  `fecha_cerrado` date DEFAULT NULL,
  `resolucion` varchar(3000) DEFAULT NULL,
  `nota` varchar(4000) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=latin1;